services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  app_producer:
    build:
      context: .
    command: bash -c "bundle exec rackup -o 0.0.0.0 -p 8080"
    depends_on:
      - rabbitmq
    ports:
      - '8080:8080'  
  # app_worker:
  #   build:
  #     context: .
  #   command: bash -c "bundle exec sneakers work Listener --require listener.rb"
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/app
