services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  app:
    build:
      context: .
    command: bash -c "bundle exec rackup -o 0.0.0.0 -p 8080 -D && bundle exec sneakers work Listener --require listener.rb"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - '8080:8080'
  oktest:
    build: 
      context: .
    environment:
      - RABBITMQ_HOST=rabbitmq
    command: bundle exec oktest test 